version: '3.8'

services:
  #----------------------------------------
  # MICROSSERVIÇO 0: AUTH SERVICE (REST)
  #----------------------------------------
  auth-service:
    image: node:20-alpine
    container_name: ocean_auth_service
    working_dir: /app/auth
    volumes:
      - ./auth-service:/app/auth
      - /app/auth/node_modules
    ports:
      - "3004:3004"
    command: sh -c "npm install && npm run dev"
    environment:
      - PORT=3004
      - NODE_ENV=development
      - CORS_ORIGINS=http://localhost:5173,http://localhost:9000

  #----------------------------------------
  # MICROSSERVIÇO 1: GAME SERVICE (Sockets)
  #----------------------------------------
  game-service:
    image: node:20-alpine
    container_name: ocean_game_service
    working_dir: /app/game
    volumes:
      - ./game-service:/app/game
      - /app/game/node_modules
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run dev"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - PUZZLE_API_URL=http://puzzle-api:3002
      - AUTH_SERVICE_URL=http://auth-service:3004
    depends_on:
      - puzzle-api
      - auth-service

  #----------------------------------------
  # MICROSSERVIÇO 2: PUZZLE API (REST)
  #----------------------------------------
  puzzle-api:
    image: node:20-alpine
    container_name: ocean_puzzle_api
    working_dir: /app/puzzle
    volumes:
      - ./puzzle-api:/app/puzzle
      - /app/puzzle/node_modules
    ports:
      - "3002:3002"
    command: sh -c "npm install && npm run dev"
    environment:
      - PORT=3002
      - NODE_ENV=development

  #----------------------------------------
  # MICROSSERVIÇO 3: SCORE SERVICE (REST + Sockets)
  #----------------------------------------
  score-service:
    image: node:20-alpine
    container_name: ocean_score_service
    working_dir: /app/score
    volumes:
      - ./score-service:/app/score
      - /app/score/node_modules
    ports:
      - "3003:3003"
    command: sh -c "npm install && npm run dev"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - GAME_SERVICE_URL=http://game-service:3001
    depends_on:
      - game-service

  #----------------------------------------
  # CLIENT: FRONTEND
  #----------------------------------------
  client:
    image: node:20-alpine
    container_name: ocean_client
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_SOCKET_URL=http://localhost:3001
      - VITE_SCORE_URL=http://localhost:3003
      - VITE_API_URL=http://localhost:3002
      - VITE_AUTH_URL=http://localhost:3004
    depends_on:
      - auth-service
      - game-service
      - puzzle-api
      - score-service