version: '3.8'

services:
  #----------------------------------------
  # MICROSSERVIÇO 1: GAME SERVICE (Sockets)
  #----------------------------------------
  game-service:
    image: node:20-alpine
    container_name: ocean_game_service
    working_dir: /app/game
    volumes:
      - ./game-service:/app/game
      - ./shared:/app/shared
      - /app/game/node_modules
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm run dev"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - PUZZLE_API_URL=http://puzzle-api:3002 #URL interna do Docker para o outro serviço

  #----------------------------------------
  # MICROSSERVIÇO 2: PUZZLE API (REST)
  #----------------------------------------
  puzzle-api:
    image: node:20-alpine
    container_name: ocean_puzzle_api
    working_dir: /app/puzzle
    volumes:
      - ./puzzle-api:/app/puzzle
      - ./shared:/app/shared
      - /app/puzzle/node_modules
    ports:
      - "3002:3002"
    command: sh -c "npm install && npm run dev"
    environment:
      - PORT=3002
      - NODE_ENV=development

  #----------------------------------------
  # CLIENT: FRONTEND
  #----------------------------------------
  client:
    image: node:20-alpine
    container_name: ocean_client
    working_dir: /app/client
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared
      - /app/client/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    environment:
      - VITE_SOCKET_URL=http://localhost:3001
      - VITE_API_URL=http://localhost:3002
    depends_on:
      - game-service
      - puzzle-api
